package Modelo;
// Generated 27/04/2016 09:13:01 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Objeto generated by hbm2java
 */
public class Objeto  implements java.io.Serializable {


     private String nombrelibro;
     private Usuario usuario;
     private String autor;
     private Integer edicion;
     private Integer anio;
     private String genero;
     private String sinopsis;
     private Integer numpaginas;
     private Set prestars = new HashSet(0);

    public Objeto() {
    }

	
    public Objeto(String nombrelibro, Usuario usuario) {
        this.nombrelibro = nombrelibro;
        this.usuario = usuario;
    }
    public Objeto(String nombrelibro, Usuario usuario, String autor, Integer edicion, Integer anio, String genero, String sinopsis, Integer numpaginas, Set prestars) {
       this.nombrelibro = nombrelibro;
       this.usuario = usuario;
       this.autor = autor;
       this.edicion = edicion;
       this.anio = anio;
       this.genero = genero;
       this.sinopsis = sinopsis;
       this.numpaginas = numpaginas;
       this.prestars = prestars;
    }
   
    public String getNombrelibro() {
        return this.nombrelibro;
    }
    
    public void setNombrelibro(String nombrelibro) {
        this.nombrelibro = nombrelibro;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getAutor() {
        return this.autor;
    }
    
    public void setAutor(String autor) {
        this.autor = autor;
    }
    public Integer getEdicion() {
        return this.edicion;
    }
    
    public void setEdicion(Integer edicion) {
        this.edicion = edicion;
    }
    public Integer getAnio() {
        return this.anio;
    }
    
    public void setAnio(Integer anio) {
        this.anio = anio;
    }
    public String getGenero() {
        return this.genero;
    }
    
    public void setGenero(String genero) {
        this.genero = genero;
    }
    public String getSinopsis() {
        return this.sinopsis;
    }
    
    public void setSinopsis(String sinopsis) {
        this.sinopsis = sinopsis;
    }
    public Integer getNumpaginas() {
        return this.numpaginas;
    }
    
    public void setNumpaginas(Integer numpaginas) {
        this.numpaginas = numpaginas;
    }
    public Set getPrestars() {
        return this.prestars;
    }
    
    public void setPrestars(Set prestars) {
        this.prestars = prestars;
    }




}


