package Modelo;
// Generated 27/04/2016 09:13:01 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Prestar generated by hbm2java
 */
public class Prestar  implements java.io.Serializable {


     private PrestarId id;
     private Objeto objeto;
     private Usuario usuarioByNombreprestador;
     private Usuario usuarioByNombreconsumidor;
     private Date fechaprestamo;
     private Integer calificacionprestador;
     private Integer calificaconsumidor;

    public Prestar() {
    }

	
    public Prestar(PrestarId id, Objeto objeto, Usuario usuarioByNombreprestador, Usuario usuarioByNombreconsumidor) {
        this.id = id;
        this.objeto = objeto;
        this.usuarioByNombreprestador = usuarioByNombreprestador;
        this.usuarioByNombreconsumidor = usuarioByNombreconsumidor;
    }
    public Prestar(PrestarId id, Objeto objeto, Usuario usuarioByNombreprestador, Usuario usuarioByNombreconsumidor, Date fechaprestamo, Integer calificacionprestador, Integer calificaconsumidor) {
       this.id = id;
       this.objeto = objeto;
       this.usuarioByNombreprestador = usuarioByNombreprestador;
       this.usuarioByNombreconsumidor = usuarioByNombreconsumidor;
       this.fechaprestamo = fechaprestamo;
       this.calificacionprestador = calificacionprestador;
       this.calificaconsumidor = calificaconsumidor;
    }
   
    public PrestarId getId() {
        return this.id;
    }
    
    public void setId(PrestarId id) {
        this.id = id;
    }
    public Objeto getObjeto() {
        return this.objeto;
    }
    
    public void setObjeto(Objeto objeto) {
        this.objeto = objeto;
    }
    public Usuario getUsuarioByNombreprestador() {
        return this.usuarioByNombreprestador;
    }
    
    public void setUsuarioByNombreprestador(Usuario usuarioByNombreprestador) {
        this.usuarioByNombreprestador = usuarioByNombreprestador;
    }
    public Usuario getUsuarioByNombreconsumidor() {
        return this.usuarioByNombreconsumidor;
    }
    
    public void setUsuarioByNombreconsumidor(Usuario usuarioByNombreconsumidor) {
        this.usuarioByNombreconsumidor = usuarioByNombreconsumidor;
    }
    public Date getFechaprestamo() {
        return this.fechaprestamo;
    }
    
    public void setFechaprestamo(Date fechaprestamo) {
        this.fechaprestamo = fechaprestamo;
    }
    public Integer getCalificacionprestador() {
        return this.calificacionprestador;
    }
    
    public void setCalificacionprestador(Integer calificacionprestador) {
        this.calificacionprestador = calificacionprestador;
    }
    public Integer getCalificaconsumidor() {
        return this.calificaconsumidor;
    }
    
    public void setCalificaconsumidor(Integer calificaconsumidor) {
        this.calificaconsumidor = calificaconsumidor;
    }




}


