package Modelo;
// Generated 27/04/2016 09:13:01 PM by Hibernate Tools 4.3.1



/**
 * PrestarId generated by hbm2java
 */
public class PrestarId  implements java.io.Serializable {


     private String nombreprestador;
     private String nombreconsumidor;
     private String nombrelibro;

    public PrestarId() {
    }

    public PrestarId(String nombreprestador, String nombreconsumidor, String nombrelibro) {
       this.nombreprestador = nombreprestador;
       this.nombreconsumidor = nombreconsumidor;
       this.nombrelibro = nombrelibro;
    }
   
    public String getNombreprestador() {
        return this.nombreprestador;
    }
    
    public void setNombreprestador(String nombreprestador) {
        this.nombreprestador = nombreprestador;
    }
    public String getNombreconsumidor() {
        return this.nombreconsumidor;
    }
    
    public void setNombreconsumidor(String nombreconsumidor) {
        this.nombreconsumidor = nombreconsumidor;
    }
    public String getNombrelibro() {
        return this.nombrelibro;
    }
    
    public void setNombrelibro(String nombrelibro) {
        this.nombrelibro = nombrelibro;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PrestarId) ) return false;
		 PrestarId castOther = ( PrestarId ) other; 
         
		 return ( (this.getNombreprestador()==castOther.getNombreprestador()) || ( this.getNombreprestador()!=null && castOther.getNombreprestador()!=null && this.getNombreprestador().equals(castOther.getNombreprestador()) ) )
 && ( (this.getNombreconsumidor()==castOther.getNombreconsumidor()) || ( this.getNombreconsumidor()!=null && castOther.getNombreconsumidor()!=null && this.getNombreconsumidor().equals(castOther.getNombreconsumidor()) ) )
 && ( (this.getNombrelibro()==castOther.getNombrelibro()) || ( this.getNombrelibro()!=null && castOther.getNombrelibro()!=null && this.getNombrelibro().equals(castOther.getNombrelibro()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getNombreprestador() == null ? 0 : this.getNombreprestador().hashCode() );
         result = 37 * result + ( getNombreconsumidor() == null ? 0 : this.getNombreconsumidor().hashCode() );
         result = 37 * result + ( getNombrelibro() == null ? 0 : this.getNombrelibro().hashCode() );
         return result;
   }   


}


