package Modelo;
// Generated 27/04/2016 09:13:01 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private String nombreusuario;
     private String contrasenia;
     private String nombre;
     private String apellidos;
     private String correo;
     private Set prestarsForNombreprestador = new HashSet(0);
     private Set prestarsForNombreconsumidor = new HashSet(0);
     private Set objetos = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(String nombreusuario) {
        this.nombreusuario = nombreusuario;
    }

    public Usuario(String nombreusuario, String contrasenia, String nombre, String apellidos, String correo) {
        this.nombreusuario = nombreusuario;
        this.contrasenia = contrasenia;
        this.nombre = nombre;
        this.apellidos = apellidos;
        this.correo = correo;
    }
    
    public Usuario(String nombreusuario, String contrasenia, String nombre, String apellidos, String correo, Set prestarsForNombreprestador, Set prestarsForNombreconsumidor, Set objetos) {
       this.nombreusuario = nombreusuario;
       this.contrasenia = contrasenia;
       this.nombre = nombre;
       this.apellidos = apellidos;
       this.correo = correo;
       this.prestarsForNombreprestador = prestarsForNombreprestador;
       this.prestarsForNombreconsumidor = prestarsForNombreconsumidor;
       this.objetos = objetos;
    }
   
    public String getNombreusuario() {
        return this.nombreusuario;
    }
    
    public void setNombreusuario(String nombreusuario) {
        this.nombreusuario = nombreusuario;
    }
    public String getContrasenia() {
        return this.contrasenia;
    }
    
    public void setContrasenia(String contrasenia) {
        this.contrasenia = contrasenia;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public Set getPrestarsForNombreprestador() {
        return this.prestarsForNombreprestador;
    }
    
    public void setPrestarsForNombreprestador(Set prestarsForNombreprestador) {
        this.prestarsForNombreprestador = prestarsForNombreprestador;
    }
    public Set getPrestarsForNombreconsumidor() {
        return this.prestarsForNombreconsumidor;
    }
    
    public void setPrestarsForNombreconsumidor(Set prestarsForNombreconsumidor) {
        this.prestarsForNombreconsumidor = prestarsForNombreconsumidor;
    }
    public Set getObjetos() {
        return this.objetos;
    }
    
    public void setObjetos(Set objetos) {
        this.objetos = objetos;
    }




}


